Repository aneoconsulting/ArmoniK.Api, pull requests merged in 2022-10, with the labels that each got.

#65 Add doc in C# index
  .github/workflows/build.yml
  Documentation/api-csharp/index.md
Labels: documentation

#62 feat: create results endpoints and messages
  Protos/V1/result_status.proto
  Protos/V1/results_common.proto
  Protos/V1/results_service.proto
Labels: enhancement

#64 ci: update files
  .github/workflows/build.yml
  .github/workflows/build_documentations.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement

#69 Update dependencies
  Api/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj
  Api/csharp/ArmoniK.Api.Common/ArmoniK.Api.Common.csproj
  Api/csharp/ArmoniK.Api.Core/ArmoniK.Api.Core.csproj
  Api/csharp/ArmoniK.Api.Tests/ArmoniK.Api.Worker.Tests.csproj
  Api/csharp/ArmoniK.Api.Worker/ArmoniK.Api.Worker.csproj
Labels: bug

#72 fix: rename sort in results to be consistant
  Protos/V1/results_common.proto
Labels: enhancement

#73 Updated PyPI send to test on main, artifact on branches and official pypi on release
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement
