Repository aneoconsulting/ArmoniK.Api, pull requests merged in 2023-04, with the labels that each got.

#213 docs: update pnpm version
  .docs/package.json
  .docs/pnpm-lock.yaml
Labels: documentation

#222 feat: Added mTLS support to C# Api
  packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj
  packages/csharp/ArmoniK.Api.Client/Options/GrpcClient.cs
  packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs
  packages/csharp/ArmoniK.Api.Common.Channel/ArmoniK.Api.Common.Channel.csproj
  packages/csharp/ArmoniK.Api.Core/ArmoniK.Api.Core.csproj
  packages/csharp/ArmoniK.Api.Worker/ArmoniK.Api.Worker.csproj
Labels: enhancement

#225 fix: added milliseconds to log
  packages/csharp/ArmoniK.Api.Common/Utils/LoggerExt.cs
Labels: enhancement

#227 fix: Fixed mTLS support for concurrent channels and .net framework support
  packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj
  packages/csharp/ArmoniK.Api.Client/Options/GrpcClient.cs
  packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs
Labels: bug, enhancement
